spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/soez_db
    username: root
    password: root

OPENAI_API_KEY: 
OPENAI_API_URL: https://api.openai.com/v1/chat/completions

weather:
  api:
    key: 
    url: http://api.openweathermap.org/data/2.5/weather?q=
